---
abstract: 'Basic Authentication module for Sledge'
author:
  - 'MATSUNO Tokuhiro E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Authorizer-BasicAuth
no_index:
  directory:
    - t
    - inc
provides:
  Sledge::Authorizer::BasicAuth:
    file: lib/Sledge/Authorizer/BasicAuth.pm
    version: 0.07
requires:
  Class::Data::Inheritable: 0.08
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
